global using CMS.Base.Internal;
global using CMS.ContentEngine.Internal;
global using CMS.DataEngine;
global using CMS.Websites;
global using CMS.Websites.Internal;
global using Kentico.Content.Web.Mvc;
global using Kentico.Content.Web.Mvc.Routing;
global using Kentico.PageBuilder.Web.Mvc;
global using Kentico.PageBuilder.Web.Mvc.Internal;
global using Kentico.Web.Mvc;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Razor.TagHelpers;
global using static PartialWidgetPage.ContextConstants;
global using static PartialWidgetPage.PartialWidgetPageConstants;